name: Build and Push

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/oliver-ni/${{ inputs.package-name }}
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=sha

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: oliver-ni
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
